/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Worker-thread client: Rust owns UDP I/O, polling, timers, and QUIC/H3 processing. */
export declare class NativeWorkerClient {
  constructor(options: JsClientOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  connect(serverAddr: string, serverName: string): JsAddressInfo
  sendRequest(headers: Array<JsHeader>, fin: boolean): number
  streamSend(streamId: number, data: Buffer, fin: boolean): boolean
  streamClose(streamId: number, errorCode: number): boolean
  close(errorCode: number, reason: string): boolean
  sendDatagram(data: Buffer): boolean
  localAddress(): JsAddressInfo
  getSessionMetrics(): JsSessionMetrics
  getRemoteSettings(): Array<JsSetting>
  ping(): boolean
  getQlogPath(): string | null
  shutdown(): void
}

export declare class NativeWorkerServer {
  constructor(options: JsServerOptions, callback: (err: Error | null, events: Array<JsH3Event>) => void)
  /**
   * Start the worker thread, binding to the given address.
   * Returns the bound address info.
   */
  listen(port: number, host: string): JsAddressInfo
  /** Send a command to the worker. Returns false if backpressure (queue full). */
  sendResponseHeaders(connHandle: number, streamId: number, headers: Array<JsHeader>, fin: boolean): boolean
  streamSend(connHandle: number, streamId: number, data: Buffer, fin: boolean): boolean
  sendTrailers(connHandle: number, streamId: number, headers: Array<JsHeader>): boolean
  streamClose(connHandle: number, streamId: number, errorCode: number): boolean
  closeSession(connHandle: number, errorCode: number, reason: string): boolean
  sendDatagram(connHandle: number, data: Buffer): boolean
  localAddress(): JsAddressInfo
  getSessionMetrics(connHandle: number): JsSessionMetrics
  getRemoteSettings(connHandle: number): Array<JsSetting>
  pingSession(connHandle: number): boolean
  getQlogPath(connHandle: number): string | null
  shutdown(): void
}

export interface JsAddressInfo {
  address: string
  family: string
  port: number
}

export interface JsClientOptions {
  ca?: Buffer
  rejectUnauthorized?: boolean
  maxIdleTimeoutMs?: number
  maxUdpPayloadSize?: number
  initialMaxData?: number
  initialMaxStreamDataBidiLocal?: number
  initialMaxStreamsBidi?: number
  sessionTicket?: Buffer
  allow0Rtt?: boolean
  enableDatagrams?: boolean
  keylog?: boolean
  qlogDir?: string
  qlogLevel?: string
}

/**
 * Metadata for rare events (new_session, error, reset).
 * Packed into a sub-object to avoid 5 null napi properties on every hot-path event.
 */
export interface JsEventMeta {
  errorCode?: number
  errorReason?: string
  remoteAddr?: string
  remotePort?: number
  serverName?: string
}

export interface JsH3Event {
  eventType: number
  connHandle: number
  streamId: number
  headers?: Array<JsHeader>
  data?: Buffer
  fin?: boolean
  meta?: JsEventMeta
  metrics?: JsSessionMetrics
}

export interface JsHeader {
  name: string
  value: string
}

export interface JsServerOptions {
  key: Buffer
  cert: Buffer
  ca?: Buffer
  maxIdleTimeoutMs?: number
  maxUdpPayloadSize?: number
  initialMaxData?: number
  initialMaxStreamDataBidiLocal?: number
  initialMaxStreamsBidi?: number
  disableActiveMigration?: boolean
  enableDatagrams?: boolean
  qpackMaxTableCapacity?: number
  qpackBlockedStreams?: number
  recvBatchSize?: number
  sendBatchSize?: number
  qlogDir?: string
  qlogLevel?: string
  sessionTicketKeys?: Buffer
  maxConnections?: number
  disableRetry?: boolean
  reusePort?: boolean
  keylog?: boolean
  quicLb?: boolean
  serverId?: Buffer
}

export interface JsSessionMetrics {
  packetsIn: number
  packetsOut: number
  bytesIn: number
  bytesOut: number
  handshakeTimeMs: number
  rttMs: number
  cwnd: number
}

export interface JsSetting {
  id: number
  value: number
}

export declare function version(): string
